<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "z3_event"
 *
 * Auto generated by Extension Builder 2014-02-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'z3_event',
	'description' => 'brickproov EventManagement with Calendar based on fluid/extbase',
	'category' => 'plugin',
	'author' => 'Sven Külpmann',
	'author_email' => 'sven.kuelpmann@lenz-wie-fruehling.de',
	'author_company' => 'Ziegelei3',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>